// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/25/2024, 12:34:32 PM
const configMerger = require("/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/plugins/**/*.{js,ts,mjs}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/composables/**/*.{js,ts,mjs}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/utils/**/*.{js,ts,mjs}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jared/Documents/sandbox/uvend/UvendWalletNuxtApp/app.config.{js,ts,mjs}"] } }));

module.exports = config
